language: c
script: cmake . && make && make test
compiler:
  - clang
  - gcc
install:
  - sudo pip install --quiet cpp-coveralls
after_success:
  - coveralls
sudo: required
addons:
  apt:
    packages:
      - cpp-coveralls
