language: c
script: cmake . && make && make test
compiler:
  - clang
  - gcc
install:
  - sudo pip install --quiet cpp-coveralls
after_success:
  - cpp-coveralls
sudo: required
#addons:
#  apt:
#    packages:
#      - cpp-coveralls
