language: c
script: cmake . -DCMAKE_BUILD_TYPE=Debug && make VERBOSE=1 && make test
compiler:
  - clang
  - gcc
install:
  - sudo -H pip install requests[security]
  - sudo -H pip install cpp-coveralls
after_success:
  - cpp-coveralls --exclude CMakeFiles --exclude examples
sudo: required
#addons:
#  apt:
#    packages:
#      - cpp-coveralls
