language: c
script: cmake . -DCMAKE_BUILD_TYPE=Debug && make && make test
compiler:
  - clang
  - gcc
install:
  - sudo pip install requests[security]
  - sudo pip install cpp-coveralls
after_success:
  - cpp-coveralls
sudo: required
#addons:
#  apt:
#    packages:
#      - cpp-coveralls
