language: c
script: cmake . -DCMAKE_BUILD_TYPE=Debug && make VERBOSE=1 && make test
compiler:
  - gcc
install:
  - sudo -H pip install requests[security]
  - pip install --user cpp-coveralls
after_success:
  - coveralls --exclude CMakeFiles --exclude examples --gcov-options '\-lp'
sudo: required
#addons:
#  apt:
#    packages:
#      - cpp-coveralls
